#!/usr/bin/env python

import discogstool.libdiscogs as libdiscogs
import discogstool.libtags as libtags
import discogstool.discogs_client as discogs_client
import discogstool.posted as posted
import os
import pprint
import sys
import argparse

print "explorer"

parser = argparse.ArgumentParser(description='Explor Artists / Labels')
parser.add_argument("-l", "--label")
parser.add_argument("-a", "--artist")
parser.add_argument("-p", "--posted", action="store_true")
args = parser.parse_args(sys.argv[1:])

if args.label:
    item = discogs_client.Label(args.label)
if args.artist:
    item = discogs_client.Artist(args.artist)

rs = item.releases
print discogs_client.tsv_key
for r in rs:
    release = libdiscogs.get_release(r["id"])
    if args.posted:
        count, price = posted.fetch_release_posted(r["id"])
        release.count = count
        release.price = price
    print release.tsv.encode("utf-8")
