#!/usr/bin/env python

import sys
import discogstool.libdiscogs as libdiscogs
import pprint

for i in sys.argv[1:]:
    r = libdiscogs.get_release(int(i))
    if r:
        print r
        pprint.pprint(r.data)
